### ISSUE TITLE
Validação do codigo 

### ISSUE THREAD

**Issue by hvilarta** [amasiero/algoritmos_estrutura_dados#1]
Professor gostaria de validar se o meu código estaria correto segue em anexo um txt com o código 
[pilha encadeada.txt](https://github.com/amasiero/algoritmos_estrutura_dados/files/1253390/pilha.encadeada.txt)

**Comment by amasiero** [comment]
Henrique, na verdade você usou, de uma certa maneira, o mesmo código da sequencial só que usando o tipo Object.

Lembra que falamos em aula de usar uma classe intermediária chamada Nó?

Tente lembra e implementar antes de ver um exemplo do código que disponibilizei aqui no repo.

Abraços.
